In [2]:
#load the library and check its version, just to make sure we aren't using an older version
import numpy as np
np.__version__


'1.19.3'

In [3]:
#creating arrays
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
#creating a matrix with a predefined value
np.full((3,5),1.23)


array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [8]:
#create an array with a set sequence
np.arange(0, 22, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[ 1.63071344e-01, -2.09068934e+00,  9.72517601e-01],
       [ 1.33927335e+00,  7.81621452e-01, -5.65175419e-02],
       [-1.03509651e+00, -2.07946983e-03,  1.98335687e+00]])

In [15]:
#create an identity matrix
3*np.eye(3)


array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [21]:
#set a random seed
print(np.random.seed(51))


None


In [ ]:


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

In [23]:
x1 = np.random.randint(10, size=6) #one dimension
x1

array([5, 4, 9, 5, 5, 4])

In [24]:
x2 = np.random.randint(10, size=(3,4)) #two dimension
x2

array([[4, 3, 6, 4],
       [6, 9, 1, 4],
       [7, 0, 8, 8]])

In [25]:
x3 = np.random.randint(10, size=(3,4,5)) #three dimension
x3

array([[[6, 4, 5, 9, 2],
        [3, 7, 7, 3, 8],
        [2, 5, 7, 1, 3],
        [5, 8, 9, 6, 5]],

       [[7, 5, 1, 4, 1],
        [1, 3, 6, 7, 2],
        [3, 4, 9, 1, 8],
        [3, 7, 3, 3, 4]],

       [[4, 4, 0, 0, 3],
        [7, 9, 5, 4, 4],
        [6, 7, 9, 8, 0],
        [4, 5, 4, 9, 2]]])

# Array Indexing


In [26]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1[0]


4

In [31]:
x1[len(x1)-1]

4

In [32]:
x1[-1]

4

In [29]:
#get the last value
x1[0]

3

In [ ]:
#get the second last value
x1[-2]

In [34]:
x2=np.array([[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0]])

#1st row and 2nd column value
x2[2,3]

0

In [39]:
x = np.arange(10,dtype='float')
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
#from start to 4th position
x[:6]

array([0., 1., 2., 3., 4., 5.])

# Array Concatenation


In [44]:
#You can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [49]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
#Using its axis parameter, you can define row-wise or column-wise matrix
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

But, what if you are required to combine a 2D array with 1D array? In such situations, np.concatenate might not be the best option to use. Instead, you can use np.vstack or np.hstack to do the task. Let's see how!


In [55]:
grid = np.array([[1,2,None],[17,18,None]])


array([[3, 4, 5],
       [1, 2, None],
       [17, 18, None]], dtype=object)

In [95]:
x = np.array([3,4,5])

gr = np.array([[1,2],[17,18]])
k = np.array([[None,None],
             [None,None]])
h = np.concatenate([gr,k],axis=1)
p1 = h[:len(x),:len(x)]


In [96]:
p1 = h[:,:len(x)]


In [98]:
p1 = h[:,:len(x)]
p1

array([[1, 2, None],
       [17, 18, None]], dtype=object)

In [103]:
#Similarly, you can add an array using np.hstack
z = np.array([[1],[9]])
grid = np.array([[1,2,3],[4,5,6]])

np.hstack([grid,z])

array([[1, 2, 3, 1],
       [4, 5, 6, 9]])